# Generated by Django 5.1.1 on 2024-09-12 19:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('type', models.CharField(choices=[('MULTITRADE', 'MULTITRADE')], default='MULTITRADE', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('max_loss', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('scrip', models.CharField(default='', max_length=100)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('stop_time', models.TimeField(default=django.utils.timezone.now)),
                ('squareoff_time', models.TimeField(default=django.utils.timezone.now)),
                ('trading_mode', models.CharField(choices=[('Paper', 'Paper'), ('Live', 'Live')], default='Paper', max_length=10)),
                ('rejection', models.BooleanField(default=False)),
                ('rejection_message', models.TextField(default='')),
                ('execute_button', models.BooleanField(default=False)),
                ('squareoff_button', models.BooleanField(default=False)),
                ('stop_button', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='backend.account')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='backend.strategy')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('instrument', models.CharField(default='', max_length=500)),
                ('trade', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='BUY', max_length=100)),
                ('qty', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('port', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='backend.port')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(default='')),
                ('level', models.CharField(choices=[('INFO', 'INFO'), ('SUCCESS', 'SUCCESS'), ('ERROR', 'ERROR')], max_length=100)),
                ('port', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='backend.port')),
            ],
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('ins_type', models.CharField(choices=[('OPT-CE', 'OPT-CE'), ('OPT-PE', 'OPT-PE'), ('FUT', 'FUT')], default='OPT', max_length=20)),
                ('expiry', models.DateField(default=django.utils.timezone.now)),
                ('trade_type', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='BUY', max_length=20)),
                ('order_type', models.CharField(choices=[('MARKET', 'MARKET'), ('LIMIT', 'LIMIT')], default='MARKET', max_length=20)),
                ('num_modifications', models.IntegerField(default=0)),
                ('modification_wait_time', models.IntegerField(default=0)),
                ('sl_on', models.CharField(choices=[('UNDERLYING', 'UNDERLYING'), ('PREMIUM', 'PREMIUM')], default='PREMIUM', max_length=20)),
                ('sl', models.CharField(default='0', max_length=10)),
                ('target', models.CharField(default='0', max_length=10)),
                ('entry_order_id', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='no_position', max_length=100)),
                ('entered_ins', models.CharField(default='', max_length=100)),
                ('entered_qty', models.IntegerField(default=0)),
                ('entered_price', models.FloatField(default=0)),
                ('entered_underlying_price', models.FloatField(default=0)),
                ('ltp', models.FloatField(default=0)),
                ('running_pnl', models.FloatField(default=0.0)),
                ('booked_pnl', models.FloatField(default=0.0)),
                ('port', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='backend.port')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='backend.user'),
        ),
    ]
