# Generated by Django 5.1.1 on 2024-09-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='account',
        ),
        migrations.AddField(
            model_name='leg',
            name='strike_distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strategy',
            name='accounts',
            field=models.ManyToManyField(to='backend.account'),
        ),
        migrations.AlterField(
            model_name='leg',
            name='ins_type',
            field=models.CharField(choices=[('OPT-CE', 'OPT-CE'), ('OPT-PE', 'OPT-PE'), ('FUT', 'FUT')], default='CE', max_length=20),
        ),
    ]
