# Generated by Django 5.1.1 on 2024-09-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_port_account_leg_strike_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('MARKET', 'MARKET'), ('LIMIT', 'LIMIT')], default='MARKET', max_length=100),
        ),
    ]
