# Generated by Django 5.1.1 on 2024-09-21 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_order_order_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='execute_button',
        ),
        migrations.RemoveField(
            model_name='port',
            name='squareoff_button',
        ),
        migrations.AddField(
            model_name='account',
            name='access_token',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='api_key',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='api_secret',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='root_url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='TradingViewAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('symbol', models.CharField(default='', max_length=50)),
                ('type', models.CharField(default='', max_length=50)),
                ('lots', models.IntegerField(default=0)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='backend.port')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='backend.strategy')),
            ],
        ),
    ]
