# Generated by Django 5.1.1 on 2024-09-29 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_port_execute_button_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leg',
            old_name='entered_qty',
            new_name='entered_lots',
        ),
        migrations.RemoveField(
            model_name='account',
            name='access_token',
        ),
        migrations.AddField(
            model_name='account',
            name='lots_multiplier',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='ws_root_url',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='leg',
            name='entered_strike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leg',
            name='entered_token',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='leg',
            name='lots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='backend.account'),
        ),
        migrations.AddField(
            model_name='port',
            name='execute_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='port',
            name='execute_button_lots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='port',
            name='squareoff_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='strategy',
            name='lots_multiplier',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strategy',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='backend.user'),
        ),
        migrations.AlterField(
            model_name='account',
            name='api_key',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='account',
            name='api_secret',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='account',
            name='root_url',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='leg',
            name='ins_type',
            field=models.CharField(choices=[('CE', 'CE'), ('PE', 'PE'), ('FUT', 'FUT')], default='CE', max_length=20),
        ),
    ]
