# Generated by Django 5.1.1 on 2024-09-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_entered_qty_leg_entered_lots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='lots_multiplier',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='lots_multiplier',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tradingviewalert',
            name='lots',
            field=models.FloatField(default=0),
        ),
    ]
