# Generated by Django 5.1.1 on 2024-09-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_account_lots_multiplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='execute_button_lots',
            field=models.FloatField(default=0),
        ),
    ]
