# Generated by Django 5.1.1 on 2024-10-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_port_execute_button_lots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leg',
            name='entered_lots',
            field=models.FloatField(default=0),
        ),
    ]
