# Generated by Django 5.1.1 on 2024-10-05 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_leg_entered_lots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leg',
            name='entered_lots',
        ),
        migrations.RemoveField(
            model_name='port',
            name='rejection',
        ),
        migrations.RemoveField(
            model_name='port',
            name='rejection_message',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='accounts',
        ),
        migrations.AddField(
            model_name='leg',
            name='executed_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leg',
            name='filled_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leg',
            name='order_status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='leg',
            name='rejection_message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='strategy',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='backend.account'),
        ),
        migrations.AlterField(
            model_name='log',
            name='level',
            field=models.CharField(choices=[('INFO', 'INFO'), ('SUCCESS', 'SUCCESS'), ('ERROR', 'ERROR'), ('PNL', 'PNL')], max_length=100),
        ),
    ]
