# Generated by Django 5.1.1 on 2025-03-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_port_scrip_type_alter_log_port'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leg',
            old_name='executed_price',
            new_name='entry_executed_price',
        ),
        migrations.RenameField(
            model_name='leg',
            old_name='filled_qty',
            new_name='entry_filled_qty',
        ),
        migrations.RenameField(
            model_name='leg',
            old_name='order_message',
            new_name='entry_order_message',
        ),
        migrations.RenameField(
            model_name='leg',
            old_name='order_status',
            new_name='entry_order_status',
        ),
        migrations.AddField(
            model_name='leg',
            name='entry_num_modifications_done',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leg',
            name='entry_order_type',
            field=models.CharField(choices=[('MARKET', 'MARKET'), ('LIMIT', 'LIMIT')], default='MARKET', max_length=20),
        ),
        migrations.AddField(
            model_name='leg',
            name='exit_executed_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leg',
            name='exit_filled_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leg',
            name='exit_num_modifications_done',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leg',
            name='exit_order_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='leg',
            name='exit_order_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='leg',
            name='exit_order_status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='leg',
            name='exit_order_type',
            field=models.CharField(choices=[('MARKET', 'MARKET'), ('LIMIT', 'LIMIT')], default='MARKET', max_length=20),
        ),
        migrations.AddField(
            model_name='leg',
            name='limit_pct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='port',
            name='combined_exit_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='port',
            name='combined_sl',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='port',
            name='combined_target',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='port',
            name='is_re_executed_port',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='port',
            name='lots_multiplier_set',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='port',
            name='to_re_execute',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='leg',
            name='lots',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='leg',
            name='modification_wait_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='port',
            name='scrip',
            field=models.CharField(default='CRUDEOIL', max_length=100),
        ),
        migrations.AlterField(
            model_name='port',
            name='scrip_type',
            field=models.CharField(default='FUT', max_length=100),
        ),
    ]
