# Generated by Django 5.1.1 on 2025-03-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_rename_executed_price_leg_entry_executed_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='actual_strike',
            field=models.IntegerField(default=0),
        ),
    ]
