# Generated by Django 5.1.1 on 2025-03-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_leg_actual_strike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leg',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='port',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
